### ISSUE TITLE
SQLite Extensions

### ISSUE THREAD

**Issue by marcusdias93** [JuliaDatabases/SQLite.jl#150]
Hi!
First, thank you for this amazing package!

I recently search a method to enable a SQLite extension and load extension in the package, but i did not find a way to do that. This request is something that is aready tracked in a "to do" list, or has no priority for now ? 
i'm trying to load the Spacialite extension for SQLite to access geo-referenced data from my database.
Thank you for your time.

**Comment by quinnj** [comment]
Hmmm, personally I'm not familiar w/ how sqlite extensions work; I thought they were something that were included at build/compile/link time w/ the sqlite shared library. If that's the case, then you would need to manage your own sqlite shared library w/ the included extensions and point SQLite.jl to use your custom shared library instead of the one it ships with. Hopefully that makes sense? If there's anything SQLite.jl the package can do to make this more convenient I'm open to ideas.

**Comment by quinnj** [comment]
It looks like there are ideas of how to do this in #151; I'll close this issue in favor of that one.
