### ISSUE TITLE
Binds not resetting

### ISSUE THREAD

**Issue by lawless-m** [JuliaDatabases/SQLite.jl#164]
using SQLite
DB = SQLite.DB()

SQLite.query(DB, "CREATE TABLE \"T\" (`a` TEXT, PRIMARY KEY (`a`))")

i = SQLite.Stmt(DB, "INSERT INTO T VALUES(?)")

try
    println("Inserting 'a'")
    SQLite.bind!(i, 1, "a")
    SQLite.execute!(i)
catch e
    println(e)
end

try
    println("Inserting 'a'")
    SQLite.bind!(i, 1, "a")
    SQLite.execute!(i)
catch e
    println(e)
end
try
    println("Inserting 'b'")
    SQLite.bind!(i, 1, "b")
    SQLite.execute!(i)
catch e
    println(e)
end

---------------OUTPUT

Inserting 'a'
Inserting 'a'
SQLite.SQLiteException("UNIQUE constraint failed: T.a")
Inserting 'b'
SQLite.SQLiteException("UNIQUE constraint failed: T.a")

--------------------------

---------------EXPECTED OUTPUT

Inserting 'a'
Inserting 'a'
SQLite.SQLiteException("UNIQUE constraint failed: T.a")
Inserting 'b'
--------------------------

**Comment by chschu** [comment]
From the [sqlite docs](https://www.sqlite.org/c3ref/bind_blob.html):

> If any of the sqlite3_bind_*() routines are called [...] with a prepared statement for which sqlite3_step() has been called more recently than sqlite3_reset(), then the call will return SQLITE_MISUSE.

It is reasonable to expect that the `Stmt` can be reused after `execute!(::Stmt)`, but that's currently not guaranteed. That's because the statement is not (always) reset in `execute!(::Stmt)`, and binding doesn't work correctly after an error (as in this case) or after a statement that returns rows.

Maybe `execute!(::Stmt)` could be changed to always reset the `Stmt` and return `nothing` instead of the sqlite result/error code? The internal calls to the method (to "step" the statement) would have to be changed, because they rely on the result/error code.

Additionally, the result of `sqlite3_bind_*()` should probably be checked for errors.

**Comment by quinnj** [comment]
Thanks @chschu for the report and research on this; it made the fix much easier! The PR w/ the fix is up here if you want to take a look: https://github.com/JuliaDatabases/SQLite.jl/pull/188.
