### ISSUE TITLE
Smart column types (enhancement - feature request)

### ISSUE THREAD

**Issue by Nosferican** [JuliaDatabases/SQLite.jl#178]
Could the column types be inferred from the db structure? For example, when a column is a `primary key` or declared as `not null`, the resulting column should be of type `T` and `Union{Missing,T}` otherwise.

```
using using SQLite: DB, execute!, Query
using DataFrames: DataFrame, eltypes
db = DB()
execute!(db, "create table x (
              id int primary key,
              a int not null,
              b int,
              c char(2) not null)")
execute!(db, "insert into x values (1, 1, 1, 'x')")
Query(db, "select * from x") |> DataFrame |> eltypes
```
That yields 
```
[Union{Missing, Int}, Union{Missing, Int}, Union{Missing, Int}, Union{Missing, String}]
```
rather than
```
[Int, Int, Union{Missing, Int}, String]
```

**Comment by quinnj** [comment]
The problem here is the sqlite engine provides very, very little info/guarantees on the types of columns in queries.

Now, what we could do is have a `SQLite.table(db, name::String)` function when you specifically want to load an sqlite table into julia. That would allow us to call the `sqlite3_table_column_metadata` function and determine if the column is `not null`. That shouldn't be too hard to add.

**Comment by Nosferican** [comment]
Could the `*` syntax, at least in the simple case of one table, work by getting the column metadata for all columns in that table?

**Comment by quinnj** [comment]
One idea that occurred to me here, is that we could drop our definition of `Tables.schema(q::Query)`, which means it would return `nothing`, and sinks would just deal with the values that are returned. In the example above, we see:
```julia
julia> df = DBInterface.execute(db, "select * from x") |> Tables.columntable
(id = [1], a = [1], b = [1], c = ["x"])
```
So the column types aren't `Union{Int, Missing}` any more, because the columns were just built up and widened as various values were encountered.

**Comment by Nosferican** [comment]
As a reference, LibPQ `not_null` option. https://invenia.github.io/LibPQ.jl/stable/pages/type-conversions/#

**Comment by quinnj** [comment]
The more I think about it, the more I like the idea of removing `Tables.schema`; for sqlite, it's so non-commital on types in general, you can basically never guarantee that a given column will have certain types of values. Removing `Tables.schema` means you always just get what you get, which is all sqlite promises anyway.
