### ISSUE TITLE
Calling `collect` outputs `missing` everywhere

### ISSUE THREAD

**Issue by ForceBru** [JuliaDatabases/SQLite.jl#239]
I'm trying to read an SQLite database created in Python. The data is written correctly, I can read it from Python and [DB Browser for SQLite](https://sqlitebrowser.org)), but `DBInterface.execute(db, "SELECT * FROM TestTable") |> collect` returns an array of rows where everything is `missing`.

--------

Python code:

```python
# sqlite_bug.py
import sqlite3
import pandas as pd

df = pd.DataFrame({'x': [1.,2,3,4], 'y': [2., 4,6,8]})

conn = sqlite3.connect('db.sqlite')
df.to_sql("TestTable", conn)
conn.close()
```

Julia code:

```julia
# sqlite_bug.jl
using SQLite

db = SQLite.DB("db.sqlite")

println(DBInterface.execute(db, "SELECT * FROM TestTable") |> collect)
```

Running this:

```
forcebru ~/test> julia sqlite_bug.jl
SQLite.Row[SQLite.Row:
 :index  missing
 :x      missing
 :y      missing, SQLite.Row:
 :index  missing
 :x      missing
 :y      missing, SQLite.Row:
 :index  missing
 :x      missing
 :y      missing, SQLite.Row:
 :index  missing
 :x      missing
 :y      missing]
forcebru ~/test>
```

---------

Using `DBInterface.execute(db, "SELECT * FROM TestTable") |> DataFrame` instead of `collect` works:

```
forcebru ~/test> julia sqlite_bug.jl
4×3 DataFrame
 Row │ index  x        y       
     │ Int64  Float64  Float64 
─────┼─────────────────────────
   1 │     0      1.0      2.0
   2 │     1      2.0      4.0
   3 │     2      3.0      6.0
   4 │     3      4.0      8.0
```

-------

Originally I wanted to use `collect` to read a single column as an array without using any 3rd-party packages like `DataFrames` and expected `collect` to return that column as an array of floats.

When I query one column with `DBInterface.execute(db, "SELECT x FROM TestTable") |> collect`, I still get an array of `SQLite.Row` where the data is `missing`:

```
SQLite.Row[SQLite.Row:
 :x  missing, SQLite.Row:
 :x  missing, SQLite.Row:
 :x  missing, SQLite.Row:
 :x  missing]
```

Is this how the `Table.jl` interface mentioned in [the docs](https://juliadatabases.org/SQLite.jl/stable/#DBInterface.execute) supposed to work for SQLite.jl? I think it's pretty confusing that `collect` returns an array of rows where the data is `missing`.

**Comment by quinnj** [comment]
Yeah, sorry for the confusion; the issue here is when iterating the results from `DBInterface.execute`, the "row" is only valid when it is the currently iterated element. This is partly an optimization thing, partly an sqlite thing. The sqlite API only allows accessing a row at a time when moving a cursor over the results; we mirror that on the Julia side and avoid materializing as a full structure to avoid excessive allocations. Unfortunately in your case, `collect` isn't a valid Tables.jl sink function. It merely allocates an array and sets each element to the iterated element. So without "saving" the current values of the iterated query row, they end up "missing" in your final array. Some valid Tables.jl functions you could consider in order to "materialize" your results are `DataFrame(query)`, or `Tables.columntable(query)`, or `Tables.rowtable(query)`.

But yeah, if you have suggestions for how we could update the docs to make things more clear, I'd appreciate suggestions or a pull request to update things.

**Comment by ForceBru** [comment]
Maybe it's possible to write a specialization of `Base.collect` that would collect a _single_ DB column into a Julia array? I'm not sure if I could suggest code for that since I'm just a user (and have little idea about the inner workings of SQLite), but from my perspective, being able to `collect` a column into a simple array would be useful. This also eliminates the need for 3rd-party packages like `DataFrames` or `Tables` when I want to read only one column.

If that doesn't make sense, I guess I should've read the documentation more carefully: I saw that the sink must conform to the Tables.jl interface but didn't know that `collect` doesn't conform to it... So, maybe it would be worth mentioning in the docs what will happen if the sink _doesn't_ support the Tables.jl interface. Getting an error in this case would be reasonable, but an array of rows of `missing` is weird, IMO.

**Comment by andyferris** [comment]
I ran into this too. Thanks for the explanation @quinnj.

I tried to use `only` (it was a single-row, metadata table that I was trying to parse manually) and then `collect` and they both have this `missing` problem. (It turns out I should have been less fancy and used `first`...).

My point is if were going to overload `collect` then there are probably other functions that need to be overloaded as well. I'm not sure what the correct generic pattern is here.
