### ISSUE TITLE
Unsupported SQLite declared type BOOLEAN

### ISSUE THREAD

**Issue by aviks** [JuliaDatabases/SQLite.jl#279]
I recieved a SQLite file from someone else. Opening it with this package caused this warning: 
```
┌ Warning: Unsupported SQLite declared type BOOLEAN, falling back to Int64 type
└ @ SQLite C:\Users\avik\.julia\packages\SQLite\5DdLp\src\SQLite.jl:402
```

I'm not that familiar with SQLite, so I'm not sure if this is an issue specific to the Julia binding? Can different SQLite bindings use different types?

**Comment by quinnj** [comment]
> 2.1. Boolean Datatype
SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).
> SQLite recognizes the keywords "TRUE" and "FALSE", as of version 3.23.0 (2018-04-02) but those keywords are really just alternative spellings for the integer literals 1 and 0 respectively.

So no, there's not an official boolean datatype. But it is true that sqlite lets you declare a column type with whatever arbitrary text string you'd like, and it's retrievable for "documentation" purposes. (see 1st paragraph [here](https://www.sqlite.org/datatypes.html)). So we could parse BOOLEAN for compat reasons, but it's a bit of whack-a-mole because people can literally put whatever they want in column names. Maybe we shouldn't warn?

**Comment by ziotom78** [comment]
> Maybe we shouldn't warn?

I like this! I have a few old SQLite3 databases containing columns declared with type `NUMBER`, and whenever I open them with Julia I get lots of warnings.

**Comment by quinnj** [comment]
Yeah, I'd be ok removing that; I think it was useful for a while because we were able to add support for some of the most common types people have, but it's true that there's no way we could cover everything since _everything_ is allowed. Would someone mind putting up a PR?

**Comment by quinnj** [comment]
Ok, warning has been removed now
